name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      CMAKE_BUILD_TYPE: Debug

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            g++ \
            libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev \
            libgstreamer-plugins-bad1.0-dev \
            libgstreamer-plugins-good1.0-dev \
            libgtest-dev

      # Create build directory
      - name: Create build directory
        run: mkdir -p build

      # Configure the project with CMake
      - name: Configure CMake
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }}

      # Build the project
      - name: Build the project
        run: cmake --build build

      # Run tests
      - name: Run tests
        run: |
          cd build/tests
          ctest --output-on-failure


